language: bash
services: docker

#install:
#  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort

script:
  - docker build -t official-images-issue-labeler .

after_script:
  - docker images

# vim:set et ts=2 sw=2:
